import type { Quadrant } from '@/radar/domain/value-objects/Quadrant';

export const categorizationMap: Record<string, Quadrant> = {
  // Frameworks y Librerías
  react: 'frameworks-librerias',
  'react-dom': 'frameworks-librerias',
  next: 'frameworks-librerias',
  'next-themes': 'frameworks-librerias',
  vue: 'frameworks-librerias',
  angular: 'frameworks-librerias',
  svelte: 'frameworks-librerias',
  'solid-js': 'frameworks-librerias',
  preact: 'frameworks-librerias',
  '@heroui/react': 'frameworks-librerias',
  '@nextui-org/react': 'frameworks-librerias',
  'framer-motion': 'frameworks-librerias',
  motion: 'frameworks-librerias',
  axios: 'frameworks-librerias',
  ky: 'frameworks-librerias',
  got: 'frameworks-librerias',
  lodash: 'frameworks-librerias',
  'lodash-es': 'frameworks-librerias',
  ramda: 'frameworks-librerias',
  immer: 'frameworks-librerias',
  'date-fns': 'frameworks-librerias',
  dayjs: 'frameworks-librerias',
  moment: 'frameworks-librerias',
  luxon: 'frameworks-librerias',
  '@material-ui/core': 'frameworks-librerias',
  '@material-ui/icons': 'frameworks-librerias',
  '@mui/material': 'frameworks-librerias',
  '@mui/icons-material': 'frameworks-librerias',
  'react-router-dom': 'frameworks-librerias',
  'react-router': 'frameworks-librerias',
  '@tanstack/react-router': 'frameworks-librerias',
  'react-hook-form': 'frameworks-librerias',
  '@hookform/resolvers': 'frameworks-librerias',
  formik: 'frameworks-librerias',
  yup: 'frameworks-librerias',
  'react-icons': 'frameworks-librerias',
  'lucide-react': 'frameworks-librerias',
  '@heroicons/react': 'frameworks-librerias',
  '@tabler/icons-react': 'frameworks-librerias',
  graphql: 'frameworks-librerias',
  '@apollo/client': 'frameworks-librerias',
  urql: 'frameworks-librerias',
  'socket.io-client': 'frameworks-librerias',
  uuid: 'frameworks-librerias',
  nanoid: 'frameworks-librerias',
  classnames: 'frameworks-librerias',
  i18next: 'frameworks-librerias',
  'react-i18next': 'frameworks-librerias',
  'next-intl': 'frameworks-librerias',
  'react-hot-toast': 'frameworks-librerias',
  sonner: 'frameworks-librerias',
  'react-toastify': 'frameworks-librerias',
  'embla-carousel-react': 'frameworks-librerias',
  swiper: 'frameworks-librerias',
  recharts: 'frameworks-librerias',
  'chart.js': 'frameworks-librerias',
  'react-chartjs-2': 'frameworks-librerias',
  d3: 'frameworks-librerias',
  'next-auth': 'frameworks-librerias',
  '@sentry/nextjs': 'frameworks-librerias',
  '@sentry/react': 'frameworks-librerias',

  // Gestión de Estado
  zustand: 'gestion-de-estado',
  redux: 'gestion-de-estado',
  '@reduxjs/toolkit': 'gestion-de-estado',
  'react-redux': 'gestion-de-estado',
  'redux-saga': 'gestion-de-estado',
  'redux-thunk': 'gestion-de-estado',
  'redux-persist': 'gestion-de-estado',
  recoil: 'gestion-de-estado',
  jotai: 'gestion-de-estado',
  valtio: 'gestion-de-estado',
  xstate: 'gestion-de-estado',
  '@xstate/react': 'gestion-de-estado',
  mobx: 'gestion-de-estado',
  'mobx-react': 'gestion-de-estado',
  'mobx-react-lite': 'gestion-de-estado',
  '@tanstack/react-query': 'gestion-de-estado',
  'react-query': 'gestion-de-estado',
  swr: 'gestion-de-estado',

  // Testing
  vitest: 'testing',
  jest: 'testing',
  '@testing-library/react': 'testing',
  '@testing-library/dom': 'testing',
  '@testing-library/jest-dom': 'testing',
  '@testing-library/user-event': 'testing',
  cypress: 'testing',
  playwright: 'testing',
  '@playwright/test': 'testing',
  msw: 'testing',
  'happy-dom': 'testing',
  jsdom: 'testing',
  '@vitest/ui': 'testing',
  '@vitest/coverage-v8': 'testing',
  'ts-jest': 'testing',
  'babel-jest': 'testing',
  supertest: 'testing',
  nock: 'testing',
  '@faker-js/faker': 'testing',
  faker: 'testing',
  sinon: 'testing',

  // Estilos y UI
  tailwindcss: 'estilos-ui',
  '@tailwindcss/postcss': 'estilos-ui',
  '@tailwindcss/typography': 'estilos-ui',
  '@tailwindcss/forms': 'estilos-ui',
  '@tailwindcss/aspect-ratio': 'estilos-ui',
  '@tailwindcss/container-queries': 'estilos-ui',
  sass: 'estilos-ui',
  less: 'estilos-ui',
  stylus: 'estilos-ui',
  'styled-components': 'estilos-ui',
  '@emotion/react': 'estilos-ui',
  '@emotion/styled': 'estilos-ui',
  '@emotion/css': 'estilos-ui',
  postcss: 'estilos-ui',
  'postcss-import': 'estilos-ui',
  autoprefixer: 'estilos-ui',
  cssnano: 'estilos-ui',
  clsx: 'estilos-ui',
  'class-variance-authority': 'estilos-ui',
  'tailwind-merge': 'estilos-ui',
  'tailwind-variants': 'estilos-ui',
  '@headlessui/react': 'estilos-ui',

  // Build Tools
  vite: 'build-tools',
  '@vitejs/plugin-react': 'build-tools',
  '@vitejs/plugin-vue': 'build-tools',
  webpack: 'build-tools',
  'webpack-cli': 'build-tools',
  esbuild: 'build-tools',
  rollup: 'build-tools',
  turbo: 'build-tools',
  parcel: 'build-tools',
  typescript: 'build-tools',
  eslint: 'build-tools',
  'eslint-config-next': 'build-tools',
  'eslint-config-prettier': 'build-tools',
  'eslint-plugin-react': 'build-tools',
  'eslint-plugin-react-hooks': 'build-tools',
  prettier: 'build-tools',
  'prettier-plugin-tailwindcss': 'build-tools',
  husky: 'build-tools',
  'lint-staged': 'build-tools',
  '@commitlint/cli': 'build-tools',
  '@commitlint/config-conventional': 'build-tools',
  tsx: 'build-tools',
  'ts-node': 'build-tools',
  zod: 'build-tools',
  '@netlify/plugin-nextjs': 'build-tools',
  '@types/node': 'build-tools',
  '@types/react': 'build-tools',
  '@types/react-dom': 'build-tools',
  '@types/jest': 'build-tools',
  '@types/lodash': 'build-tools',
  'cross-env': 'build-tools',
  dotenv: 'build-tools',
  'npm-run-all': 'build-tools',
  concurrently: 'build-tools',
  nx: 'build-tools',
  lerna: 'build-tools',
  storybook: 'build-tools',
  'react-scripts': 'build-tools',
};

/**
 * Reglas por prefijo para familias de paquetes con convención de nombre predecible
 * (scopes de npm, plugins de ESLint/Babel/Vite, etc.). Se evalúan solo si el nombre
 * exacto no está en `categorizationMap`, para cubrir variantes no listadas explícitamente
 * (ej. `@radix-ui/react-dialog`, `eslint-plugin-import`, `@babel/preset-typescript`).
 */
const prefixRules: ReadonlyArray<readonly [string, Quadrant]> = [
  ['@types/', 'build-tools'],
  ['@typescript-eslint/', 'build-tools'],
  ['eslint-plugin-', 'build-tools'],
  ['eslint-config-', 'build-tools'],
  ['@babel/', 'build-tools'],
  ['babel-plugin-', 'build-tools'],
  ['babel-preset-', 'build-tools'],
  ['@vitejs/', 'build-tools'],
  ['vite-plugin-', 'build-tools'],
  ['@storybook/', 'build-tools'],
  ['@commitlint/', 'build-tools'],
  ['@testing-library/', 'testing'],
  ['jest-', 'testing'],
  ['@playwright/', 'testing'],
  ['@emotion/', 'estilos-ui'],
  ['@radix-ui/', 'estilos-ui'],
  ['@headlessui/', 'estilos-ui'],
  ['@heroui/', 'frameworks-librerias'],
  ['@nextui-org/', 'frameworks-librerias'],
  ['@mui/', 'frameworks-librerias'],
  ['@material-ui/', 'frameworks-librerias'],
  ['@sentry/', 'frameworks-librerias'],
  ['@reduxjs/', 'gestion-de-estado'],
  ['redux-', 'gestion-de-estado'],
];

export function categorizePackage(packageName: string): Quadrant {
  const exact = categorizationMap[packageName];
  if (exact) return exact;

  const rule = prefixRules.find(([prefix]) => packageName.startsWith(prefix));
  return rule ? rule[1] : 'sin-categorizar';
}
